### ISSUE TITLE
Build Error on iOS Simulator with ReactBridge

### ISSUE THREAD

**Issue by floydkim** [ikhvorost/ReactBridge#11]
Hi, thank you for creating such a convenient tool.

I encountered the following error when trying to build on the iOS simulator:

<img width="565" alt="image" src="https://github.com/user-attachments/assets/0c4cbc05-878b-411a-b0e9-35939f36211e">

<img width="532" alt="image" src="https://github.com/user-attachments/assets/48652cb6-f65f-4a4a-b45e-d7a6f67911f6">

I did not face this issue when building on a real device.

As a beginner in iOS development, I’m not sure if this is an issue with my environment or if it’s something that needs to be supported by the ReactBridge package.

Xcode version: 15.4
ReactBridge package version: 1.2.0 (latest)
React Native version: 0.73.8

**Comment by ikhvorost** [comment]
Hi!

ReactBridge is delivered as a library with source code and can be compiled for any needed platforms and works both real devices or simulators.

In your case try the following:
1) Do `Product` > `Clean Build Folder` (Shift + Cmd + K)
2) Do `File` > `Packages` >`Reset Package Caches`
3) Quit Xcode or reboot your Mac

If it doesn't help you can try to delete DerivedData folder manually or remove and then add the package.

**Comment by floydkim** [comment]
@ikhvorost 
Thank you for your quick response. I tried what you suggested, but the issue wasn’t resolved.
However, when I changed the build target to the Rosetta simulator, the problem disappeared.
<img width="180" alt="image" src="https://github.com/user-attachments/assets/f567d9c9-d856-45f6-a589-501d31165710">


> ReactBridge is delivered as a library with source code and can be compiled for any needed platforms and works both real devices or simulators.

I agree with you. but I don’t understand why it fails for a non-Rosetta.
Is there any way to successfully build for a non-Rosetta simulator target as well?

**Comment by floydkim** [comment]
I Googled and found a hint. ([this](https://forums.developer.apple.com/forums/thread/730022))
I tried building on a different device simulator (iPhone SE 3rd generation), and the build error did not occur.
But I encountered a runtime error where it couldn’t find the native components.
`ERROR  Invariant Violation: requireNativeComponent: "ImageSliderView" was not found in the UIManager.`

so... it seems using the Rosetta simulator will make everyone happy.
However, using ReactBridge in a project where I collaborate with my colleagues might introduce some constraints for them, making me hesitant to adopt it.

**Comment by ikhvorost** [comment]
I use ReactBridge in my test and real projects and can compile and run on devices and arm/x86 simulators with no issues. So maybe your case is related to your project's configuration or your project has binary dependency with x86 simulator only and it causes the error on ReactBridge.

Try to make new clear sample app for React Native and add ReactBridge to test and verify.

**Comment by floydkim** [comment]
I agree. it seems like the issue is related to my project’s configuration.

Thanks for the quick and friendly response.
I’ll close the issue 😃
