### ISSUE TITLE
`@ReactView` with `@ReactProperty` that has a type of `RCTDirectEventBlock`

### ISSUE THREAD

**Issue by Brett-Best** [ikhvorost/ReactBridge#7]
Hi,

I'm trying to migrate the below:
```objc
#import <React/RCTViewManager.h>
#import "React/RCTBridgeModule.h"
 
@interface RCT_EXTERN_MODULE(NativeAppViewManager, RCTViewManager)
RCT_EXPORT_VIEW_PROPERTY(onNavUpdate, RCTDirectEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onNavBack, RCTDirectEventBlock)
RCT_EXPORT_VIEW_PROPERTY(screenOptions, NSDictionary *)
RCT_EXTERN_METHOD(create: (nonnull NSNumber *) node)
RCT_EXTERN_METHOD(navigate: (nonnull NSNumber *) node action: (nonnull NSDictionary *) action)
RCT_EXTERN_METHOD(navigateMulti: (nonnull NSNumber *) node actions: (nonnull NSArray *) actions)
@end
```

I got this far and hit the error: `ReactBridge: 'RCTDirectEventBlock' type is not supported`
```swift
@ReactView
class NativeAppViewManager: RCTViewManager {
    @ReactProperty var onNavUpdate: RCTDirectEventBlock?
```

Would you have any ideas of a workaround? Or where a fix would need to be made either in the code above or in the macro?
Thanks so much 💜

**Comment by Brett-Best** [comment]
I made a change similar to the support for `RCTBubblingEventBlock` here https://github.com/Brett-Best/ReactBridge/commit/ccdff7b74ea6df26aa6ec4b3475414808a0da693

**Comment by ikhvorost** [comment]
You can use `RCTBubblingEventBlock` instead of `RCTDirectEventBlock` because they have equal signatures but I consider adding those types to new release.

**Comment by ikhvorost** [comment]
The types are added to [1.1.0](https://github.com/ikhvorost/ReactBridge/releases/tag/1.1.0). Thanks.

**Comment by Brett-Best** [comment]
Thanks 💜
